name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: my-app

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Build and Push Image
      run: |
        docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ github.sha }} .
        docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:${{ github.sha }}

    - name: Set kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/my-app my-app=$DOCKERHUB_USERNAME/$IMAGE_NAME:${{ github.sha }}
        kubectl rollout status deployment/my-app
